[package]
edition = "2021"
name = "shake-multihash"
version = "0.1.0"

[dependencies]
core2 = "0.4.0"
multihash = "0.18.1"
sha3 = "0.10.8"

[dev-dependencies]
amcl_wrapper = {version = "0.4.0", features = ["bls381"]}
cid = "0.10.1"
multibase = "0.9.1"
